### ISSUE TITLE
Achmea doesn't offer bounties

### ISSUE THREAD

**Issue by Xitro01** [projectdiscovery/public-bugbounty-programs#861]
Achmea doesn't seem to give out bounties, they offer swag.
So bounty should be false and swag should be true.

**Comment by SvenKiljan** [comment]
Achmea is not participating in any bug bounty programs at this time. Part of the [responsible disclosure procedure](https://achmea.nl/en/responsibledisclosure) is a reward program. Currently the possible offer consists of:

* A mention in [Achmea's responsible disclosure hall of fame](https://www.achmea.nl/en/responsible-disclosure/hall-of-fame)
* Swag, as noted by @Xitro01. The swag consists of a T-shirt.
* Gift coupons with a noted maximum value.

What is offered depends on several factors noted on the responsible disclosure page.

Currently the entry for Achmea shows:
![image](https://github.com/user-attachments/assets/9a0cb82b-900a-4bd4-a4d4-4233c840e53d)

Swag probably should be "yes", since T-shirts are part of the reward program. It is unclear to me whether gift coupons are considered a "reward", so I do not know if the current entry is correct in that regard.

**Comment by Xitro01** [comment]
> Achmea is not participating in any bug bounty programs at this time. Part of the [responsible disclosure procedure](https://achmea.nl/en/responsibledisclosure) is a reward program. Currently the possible offer consists of:
> 
> * A mention in [Achmea's responsible disclosure hall of fame](https://www.achmea.nl/en/responsible-disclosure/hall-of-fame)
> * Swag, as noted by @Xitro01. The swag consists of a T-shirt.
> * Gift coupons with a noted maximum value.
> 
> What is offered depends on several factors noted on the responsible disclosure page.
> 
> Currently the entry for Achmea shows: ![image](https://private-user-images.githubusercontent.com/30316357/349811470-9a0cb82b-900a-4bd4-a4d4-4233c840e53d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyODEzNDEsIm5iZiI6MTcyMTI4MTA0MSwicGF0aCI6Ii8zMDMxNjM1Ny8zNDk4MTE0NzAtOWEwY2I4MmItOTAwYS00YmQ0LWE0ZDQtNDIzM2M4NDBlNTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDA1MzcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0NjMxMjJjNDQzYTJiMTRmZGJiMjFiZjFlNDZmYTBhMzc1NzY4NTVlYjA4ZjBmZjI2N2I0ZDQ5ODcwYjZlZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._dLtpz6LCxCccVt8ueCG4ZqPtckoIi6ooZ2jgxo4kw4)
> 
> Swag probably should be "yes", since T-shirts are part of the reward program. It is unclear to me whether gift coupons are considered a "reward", so I do not know if the current entry is correct in that regard.

Thanks for further clarifying! Also the chances of getting a gift card is very slim. So I would say swag yes and reward no.

**Comment by SvenKiljan** [comment]
> Thanks for further clarifying! Also the chances of getting a gift card is very slim. So I would say swag yes and reward no.

Gift cards are the highest tier of reward currently offered. They are offered, but only for findings that are severe and for which an appropriate amount of effort was required to find and confirm.

Using OSINT to search for services that report a version number which might be vulnerable to a recently discovered exploit is not considered an appropriate amount of effort. Neither does that confirm actual vulnerabilities. Of course, such responsible disclosure reports are still welcome independent of how the reward program applies.
